version: 1.0.0-build{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
branches:
    only:
        - master
after_build:
- ps: dotnet publish -c Release -r win-x64 -o "../$env:APPVEYOR_PROJECT_NAME-$env:APPVEYOR_REPO_COMMIT-win-x64"
- ps: dotnet publish -c Release -r win-x86 -o "../$env:APPVEYOR_PROJECT_NAME-$env:APPVEYOR_REPO_COMMIT-win-x86"
- ps: dotnet publish -c Release -r ubuntu-x64 -o "../$env:APPVEYOR_PROJECT_NAME-$env:APPVEYOR_REPO_COMMIT-ubuntu-x64"
- ps: dotnet publish -c Release -o "../$env:APPVEYOR_PROJECT_NAME-$env:APPVEYOR_REPO_COMMIT-all-x64"
- ps: Get-ChildItem $env:APPVEYOR_PROJECT_NAME-* | % { 7z a -tzip $_.Name $_.FullName }
- ps: Get-ChildItem *.zip | % { Push-AppveyorArtifact $_.FullName }
